global:
  name: train-matrn-finetune-HPC-vision-5more 
  phase: train
  stage: train-super
  workdir: workdir_Final_HPC
  seed: ~
 
dataset:
  train: {
    roots: [data/training/MJ/train/', 
            'data/training/MJ/test/', 
            'data/training/MJ/val/', 
            'data/training/ST'],
    batch_size: 384
  }
  test: {
    roots: ['data/test/IIIT5k', 
            'data/test/SVT', 
            'data/test/SVTP',
            'data/test/IC13_857',
            'data/test/IC15_1811',
            'data/test/CUTE80'],
    batch_size: 384
  }
  valid: {
    roots: ['data/test/IC15_1811',
            'data/test/CUTE80'],
    batch_size: 384
  }
  charset_path: data/charset_94.txt
  max_length: 35
  data_aug: True
  case_sensitive: True
  eval_case_sensitive: True
  multiscales: False
  num_workers: 50

training:
  epochs: 10
  show_iters: 50
  eval_iters: 3000
  save_iters: 3000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [6, 4],
    gamma: 0.1,
  }

model:
  name: 'modules.model_matrn_iter.MATRN'
  iter_size: 3
  ensemble: ''
  use_vision: False
  vision: {
    checkpoint: workdir/pretrain-vision-model/pretrain-vision-model.pth,
    loss_weight: 1.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
  }
  language: {
    checkpoint: /workdir/pretrain-language-model/pretrain-language-model.pth,
    num_layers: 4,
    loss_weight: 1.,
    detach: True,
    use_self_attn: False
  }
  alignment: {
    checkpoint: ,
    num_layers: 2,
    loss_weight: 1.,
    use_self_attn: False,
  }
